FROM node:18

WORKDIR /app

COPY package*.json ./

RUN npm install
RUN npm i --save validator class-validator class-transformer

COPY . .

RUN npm run build
EXPOSE 3000

CMD [ "npm", "run", "start:dev" ]